### Adult imcome with XGBoost Classifier

In [49]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

In [27]:
data_ds = pd.read_csv('./adult.csv', header=None)

In [28]:
data_ds

0                  1       2            3   4                    5   \
0      39          State-gov   77516    Bachelors  13        Never-married   
1      50   Self-emp-not-inc   83311    Bachelors  13   Married-civ-spouse   
2      38            Private  215646      HS-grad   9             Divorced   
3      53            Private  234721         11th   7   Married-civ-spouse   
4      28            Private  338409    Bachelors  13   Married-civ-spouse   
...    ..                ...     ...          ...  ..                  ...   
32556  27            Private  257302   Assoc-acdm  12   Married-civ-spouse   
32557  40            Private  154374      HS-grad   9   Married-civ-spouse   
32558  58            Private  151910      HS-grad   9              Widowed   
32559  22            Private  201490      HS-grad   9        Never-married   
32560  52       Self-emp-inc  287927      HS-grad   9   Married-civ-spouse   

                       6               7       8        9      10  11  12  \
0            Adm-clerical   Not-in-family   White     Male   2174   0  40   
1         Exec-managerial         Husband   White     Male      0   0  13   
2       Handlers-cleaners   Not-in-family   White     Male      0   0  40   
3       Handlers-cleaners         Husband   Black     Male      0   0  40   
4          Prof-specialty            Wife   Black   Female      0   0  40   
...                   ...             ...     ...      ...    ...  ..  ..   
32556        Tech-support            Wife   White   Female      0   0  38   
32557   Machine-op-inspct         Husband   White     Male      0   0  40   
32558        Adm-clerical       Unmarried   White   Female      0   0  40   
32559        Adm-clerical       Own-child   White     Male      0   0  20   
32560     Exec-managerial            Wife   White   Female  15024   0  40   

                   13      14  
0       United-States   <=50K  
1       United-States   <=50K  
2       United-States   <=50K  
3       United-States   <=50K  
4                Cuba   <=50K  
...               ...     ...  
32556   United-States   <=50K  
32557   United-States    >50K  
32558   United-States   <=50K  
32559   United-States   <=50K  
32560   United-States    >50K  

[32561 rows x 15 columns]

In [29]:
data_ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   0       32561 non-null  int64 
 1   1       32527 non-null  object
 2   2       32561 non-null  int64 
 3   3       32561 non-null  object
 4   4       32561 non-null  int64 
 5   5       32561 non-null  object
 6   6       32532 non-null  object
 7   7       32561 non-null  object
 8   8       32561 non-null  object
 9   9       32561 non-null  object
 10  10      32561 non-null  int64 
 11  11      32561 non-null  int64 
 12  12      32561 non-null  int64 
 13  13      32560 non-null  object
 14  14      32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [30]:
data_ds.isnull().sum()

0      0
1     34
2      0
3      0
4      0
5      0
6     29
7      0
8      0
9      0
10     0
11     0
12     0
13     1
14     0
dtype: int64

In [31]:
data_ds.isna().sum()

0      0
1     34
2      0
3      0
4      0
5      0
6     29
7      0
8      0
9      0
10     0
11     0
12     0
13     1
14     0
dtype: int64

In [32]:
X = data_ds.iloc[:, :-1].values
y = data_ds.iloc[:, -1]

In [17]:
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
X[:, 1:] = imputer.fit_transform(X[:, 1:])

In [18]:
X

array([[39, ' State-gov', 77516, ..., 0, 40, ' United-States'],
       [50, ' Self-emp-not-inc', 83311, ..., 0, 13, ' United-States'],
       [38, ' Private', 215646, ..., 0, 40, ' United-States'],
       ...,
       [58, ' Private', 151910, ..., 0, 40, ' United-States'],
       [22, ' Private', 201490, ..., 0, 20, ' United-States'],
       [52, ' Self-emp-inc', 287927, ..., 0, 40, ' United-States']],
      dtype=object)

In [40]:
encoder_1 = LabelEncoder()
X[:, 1] = encoder_1.fit_transform(X[:, 1])

encoder_3 = LabelEncoder()
X[:, 3] = encoder_3.fit_transform(X[:, 3])

encoder_5 = LabelEncoder()
X[:, 5] = encoder_5.fit_transform(X[:, 5])

encoder_6 = LabelEncoder()
X[:, 6] = encoder_6.fit_transform(X[:, 6])

encoder_7 = LabelEncoder()
X[:, 7] = encoder_7.fit_transform(X[:, 7])

encoder_8 = LabelEncoder()
X[:, 8] = encoder_8.fit_transform(X[:, 8])

encoder_9 = LabelEncoder()
X[:, 9] = encoder_9.fit_transform(X[:, 9])

encoder_13 = LabelEncoder()
X[:, 13] = encoder_13.fit_transform(X[:, 13])

encoder_y = LabelEncoder()
y = encoder_y.fit_transform(y)

In [41]:
X

array([[39, 7, 77516, ..., 0, 40, 39],
       [50, 6, 83311, ..., 0, 13, 39],
       [38, 4, 215646, ..., 0, 40, 39],
       ...,
       [58, 4, 151910, ..., 0, 40, 39],
       [22, 4, 201490, ..., 0, 20, 39],
       [52, 5, 287927, ..., 0, 40, 39]], dtype=object)

In [42]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [43]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((26048, 14), (6513, 14), (26048,), (6513,))

In [44]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X=X_train)
X_test = scaler.fit_transform(X=X_test)

In [46]:
model = XGBClassifier()

In [47]:
model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [48]:
model.score(X_train, y_train)

0.9083614864864865

In [51]:
y_pred = model.predict(X_test)

In [52]:
acc = accuracy_score(y_true=y_test, y_pred=y_pred)
acc

0.8317211730385383

In [53]:
cm = confusion_matrix(y_true=y_test, y_pred=y_pred)

In [54]:
cm

array([[4812,  130],
       [ 966,  605]], dtype=int64)

In [55]:
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [1 1]
 ...
 [1 1]
 [0 0]
 [0 0]]


In [58]:
# age=40, workclass=private, employ_inc=80000, bachelor,9,divorced, Exec-managerial,Husband, white,male,0,1000,50,united-state

result=model.predict(scaler.transform([[40,4,80000,9,9,0,4,0,4,1,0,1000,50,39]]))
if result==[0]:
  print('makes Below 50K/year')
else:
  print('makes Above 50K/year')



makes Below 50K/year
