### Car price predication with `RandomForestRegressor`

In [51]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

In [16]:
data_ds = pd.read_csv('./Car_Price_data_set/audi.csv')
data_ds.head(5)

model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0    A1  2017  12500       Manual    15735   Petrol  150  55.4         1.4
1    A6  2016  16500    Automatic    36203   Diesel   20  64.2         2.0
2    A1  2016  11000       Manual    29946   Petrol   30  55.4         1.4
3    A4  2017  16800    Automatic    25952   Diesel  145  67.3         2.0
4    A3  2019  17300       Manual     1998   Petrol  145  49.6         1.0

In [17]:
data_ds.isnull().sum()

model           0
year            0
price           0
transmission    0
mileage         0
fuelType        0
tax             0
mpg             0
engineSize      0
dtype: int64

In [18]:
data_ds.isna().sum()

model           0
year            0
price           0
transmission    0
mileage         0
fuelType        0
tax             0
mpg             0
engineSize      0
dtype: int64

In [19]:
X = data_ds.drop(columns='price', axis=1)
X

model  year transmission  mileage fuelType  tax   mpg  engineSize
0        A1  2017       Manual    15735   Petrol  150  55.4         1.4
1        A6  2016    Automatic    36203   Diesel   20  64.2         2.0
2        A1  2016       Manual    29946   Petrol   30  55.4         1.4
3        A4  2017    Automatic    25952   Diesel  145  67.3         2.0
4        A3  2019       Manual     1998   Petrol  145  49.6         1.0
...     ...   ...          ...      ...      ...  ...   ...         ...
10663    A3  2020       Manual     4018   Petrol  145  49.6         1.0
10664    A3  2020       Manual     1978   Petrol  150  49.6         1.0
10665    A3  2020       Manual      609   Petrol  150  49.6         1.0
10666    Q3  2017    Automatic     8646   Petrol  150  47.9         1.4
10667    Q3  2016       Manual    11855   Petrol  150  47.9         1.4

[10668 rows x 8 columns]

In [20]:
y = data_ds['price']
y

0        12500
1        16500
2        11000
3        16800
4        17300
         ...  
10663    16999
10664    16999
10665    17199
10666    19499
10667    15999
Name: price, Length: 10668, dtype: int64

In [21]:
print(X)

      model  year transmission  mileage fuelType  tax   mpg  engineSize
0        A1  2017       Manual    15735   Petrol  150  55.4         1.4
1        A6  2016    Automatic    36203   Diesel   20  64.2         2.0
2        A1  2016       Manual    29946   Petrol   30  55.4         1.4
3        A4  2017    Automatic    25952   Diesel  145  67.3         2.0
4        A3  2019       Manual     1998   Petrol  145  49.6         1.0
...     ...   ...          ...      ...      ...  ...   ...         ...
10663    A3  2020       Manual     4018   Petrol  145  49.6         1.0
10664    A3  2020       Manual     1978   Petrol  150  49.6         1.0
10665    A3  2020       Manual      609   Petrol  150  49.6         1.0
10666    Q3  2017    Automatic     8646   Petrol  150  47.9         1.4
10667    Q3  2016       Manual    11855   Petrol  150  47.9         1.4

[10668 rows x 8 columns]


In [22]:
print(y)

0        12500
1        16500
2        11000
3        16800
4        17300
         ...  
10663    16999
10664    16999
10665    17199
10666    19499
10667    15999
Name: price, Length: 10668, dtype: int64


In [30]:
X = X.to_numpy()

In [31]:
encoder_0 = LabelEncoder()
X[:,0] = encoder_0.fit_transform(X[:,0])

encoder_4 = LabelEncoder()
X[:,4] = encoder_4.fit_transform(X[:,4])

In [36]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [2])], remainder='passthrough')

In [37]:
ct

ColumnTransformer(remainder='passthrough',
                  transformers=[('encoder', OneHotEncoder(), [2])])

In [38]:
X = ct.fit_transform(X)

In [39]:
X

array([[0.0, 1.0, 0.0, ..., 150, 55.4, 1.4],
       [1.0, 0.0, 0.0, ..., 20, 64.2, 2.0],
       [0.0, 1.0, 0.0, ..., 30, 55.4, 1.4],
       ...,
       [0.0, 1.0, 0.0, ..., 150, 49.6, 1.0],
       [1.0, 0.0, 0.0, ..., 150, 47.9, 1.4],
       [0.0, 1.0, 0.0, ..., 150, 47.9, 1.4]], dtype=object)

In [41]:
scaler = StandardScaler()
X = scaler.fit_transform(X)
X

array([[-0.58326752,  1.2007284 , -0.71233307, ...,  0.35714729,
         0.35755001, -0.88021837],
       [ 1.71447913, -0.83282781, -0.71233307, ..., -1.57832278,
         1.03713001,  0.11492465],
       [-0.58326752,  1.2007284 , -0.71233307, ..., -1.42944047,
         0.35755001, -0.88021837],
       ...,
       [-0.58326752,  1.2007284 , -0.71233307, ...,  0.35714729,
        -0.09035499, -1.54364705],
       [ 1.71447913, -0.83282781, -0.71233307, ...,  0.35714729,
        -0.22163749, -0.88021837],
       [-0.58326752,  1.2007284 , -0.71233307, ...,  0.35714729,
        -0.22163749, -0.88021837]])

In [43]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [44]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((8534, 10), (2134, 10), (8534,), (2134,))

In [46]:
model = RandomForestRegressor(n_estimators=120, random_state=42)

In [47]:
model.fit(X=X_train, y=y_train)

RandomForestRegressor(n_estimators=120, random_state=42)

In [48]:
model.score(X=X_train, y=y_train)

0.9938457863468522

In [49]:
y_pred = model.predict(X=X_test)
y_pred

array([ 8936.91666667, 20772.25      , 29838.14895833, ...,
       16505.15833333, 20553.83333333, 10772.59166667])

In [52]:
r2 = r2_score(y_true=y_test, y_pred=y_pred)
r2

0.9634023013670389

In [56]:
y_pred_reshaped = np.reshape(y_pred, (-1, 1))